<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="6" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="80" started-at="2016-02-16T15:33:35Z" finished-at="2016-02-16T15:33:35Z">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="80" started-at="2016-02-16T15:33:35Z" finished-at="2016-02-16T15:33:35Z">
      <class name="se.nrm.dina.data.exceptions.ErrorMsgNGTest">
        <test-method status="PASS" signature="testGetEntityNameErrorMsg()[pri:0, instance:se.nrm.dina.data.exceptions.ErrorMsgNGTest@66596a88]" name="testGetEntityNameErrorMsg" duration-ms="1" started-at="2016-02-16T16:33:35Z" finished-at="2016-02-16T16:33:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetEntityNameErrorMsg -->
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:se.nrm.dina.data.exceptions.ErrorMsgNGTest@66596a88]" name="setUpClass" is-config="true" duration-ms="0" started-at="2016-02-16T16:33:35Z" finished-at="2016-02-16T16:33:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="PASS" signature="testGetInstance()[pri:0, instance:se.nrm.dina.data.exceptions.ErrorMsgNGTest@66596a88]" name="testGetInstance" duration-ms="0" started-at="2016-02-16T16:33:35Z" finished-at="2016-02-16T16:33:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetInstance -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:se.nrm.dina.data.exceptions.ErrorMsgNGTest@66596a88]" name="tearDownClass" is-config="true" duration-ms="0" started-at="2016-02-16T16:33:35Z" finished-at="2016-02-16T16:33:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- se.nrm.dina.data.exceptions.ErrorMsgNGTest -->
      <class name="se.nrm.dina.data.exceptions.DinaExceptionNGTest">
        <test-method status="PASS" signature="testDinaExceptionConstruct()[pri:0, instance:se.nrm.dina.data.exceptions.DinaExceptionNGTest@65fd6708]" name="testDinaExceptionConstruct" duration-ms="34" started-at="2016-02-16T16:33:35Z" finished-at="2016-02-16T16:33:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDinaExceptionConstruct -->
        <test-method status="PASS" signature="testDinaExceptionConstructWithMsg()[pri:0, instance:se.nrm.dina.data.exceptions.DinaExceptionNGTest@65fd6708]" name="testDinaExceptionConstructWithMsg" duration-ms="1" started-at="2016-02-16T16:33:35Z" finished-at="2016-02-16T16:33:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDinaExceptionConstructWithMsg -->
        <test-method status="PASS" signature="testDinaExceptionConstructWithMsgAndErrorCode()[pri:0, instance:se.nrm.dina.data.exceptions.DinaExceptionNGTest@65fd6708]" name="testDinaExceptionConstructWithMsgAndErrorCode" duration-ms="0" started-at="2016-02-16T16:33:35Z" finished-at="2016-02-16T16:33:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDinaExceptionConstructWithMsgAndErrorCode -->
        <test-method status="PASS" signature="testGetErrorCode()[pri:0, instance:se.nrm.dina.data.exceptions.DinaExceptionNGTest@65fd6708]" name="testGetErrorCode" duration-ms="0" started-at="2016-02-16T16:33:35Z" finished-at="2016-02-16T16:33:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetErrorCode -->
      </class> <!-- se.nrm.dina.data.exceptions.DinaExceptionNGTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
