<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="6" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="70" started-at="2016-02-10T16:35:32Z" finished-at="2016-02-10T16:35:32Z">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="70" started-at="2016-02-10T16:35:32Z" finished-at="2016-02-10T16:35:32Z">
      <class name="se.nrm.dina.data.exceptions.ErrorMsgNGTest">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:se.nrm.dina.data.exceptions.ErrorMsgNGTest@6b3871d6]" name="setUpClass" is-config="true" duration-ms="0" started-at="2016-02-10T17:35:32Z" finished-at="2016-02-10T17:35:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="PASS" signature="testGetEntityNameErrorMsg()[pri:0, instance:se.nrm.dina.data.exceptions.ErrorMsgNGTest@6b3871d6]" name="testGetEntityNameErrorMsg" duration-ms="2" started-at="2016-02-10T17:35:32Z" finished-at="2016-02-10T17:35:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetEntityNameErrorMsg -->
        <test-method status="PASS" signature="testGetInstance()[pri:0, instance:se.nrm.dina.data.exceptions.ErrorMsgNGTest@6b3871d6]" name="testGetInstance" duration-ms="0" started-at="2016-02-10T17:35:32Z" finished-at="2016-02-10T17:35:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetInstance -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:se.nrm.dina.data.exceptions.ErrorMsgNGTest@6b3871d6]" name="tearDownClass" is-config="true" duration-ms="0" started-at="2016-02-10T17:35:32Z" finished-at="2016-02-10T17:35:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- se.nrm.dina.data.exceptions.ErrorMsgNGTest -->
      <class name="se.nrm.dina.data.exceptions.DinaExceptionNGTest">
        <test-method status="PASS" signature="testDinaExceptionConstruct()[pri:0, instance:se.nrm.dina.data.exceptions.DinaExceptionNGTest@6be25526]" name="testDinaExceptionConstruct" duration-ms="27" started-at="2016-02-10T17:35:32Z" finished-at="2016-02-10T17:35:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDinaExceptionConstruct -->
        <test-method status="PASS" signature="testDinaExceptionConstructWithMsg()[pri:0, instance:se.nrm.dina.data.exceptions.DinaExceptionNGTest@6be25526]" name="testDinaExceptionConstructWithMsg" duration-ms="0" started-at="2016-02-10T17:35:32Z" finished-at="2016-02-10T17:35:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDinaExceptionConstructWithMsg -->
        <test-method status="PASS" signature="testGetErrorCode()[pri:0, instance:se.nrm.dina.data.exceptions.DinaExceptionNGTest@6be25526]" name="testGetErrorCode" duration-ms="1" started-at="2016-02-10T17:35:32Z" finished-at="2016-02-10T17:35:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetErrorCode -->
        <test-method status="PASS" signature="testDinaExceptionConstructWithMsgAndErrorCode()[pri:0, instance:se.nrm.dina.data.exceptions.DinaExceptionNGTest@6be25526]" name="testDinaExceptionConstructWithMsgAndErrorCode" duration-ms="0" started-at="2016-02-10T17:35:32Z" finished-at="2016-02-10T17:35:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDinaExceptionConstructWithMsgAndErrorCode -->
      </class> <!-- se.nrm.dina.data.exceptions.DinaExceptionNGTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
